version: '3.8'

services:
  db:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: quizmaster
      POSTGRES_PASSWORD: pgsecret
      POSTGRES_DB: pgquiz
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
  